### ISSUE TITLE
Update to 1.19.2 please

### ISSUE THREAD

**Issue by JoMei9019-real** [LimeShulkerBox/multiplayer-button#1]
Please update this mod to 1.19.2

**Comment by piemanau** [comment]
If I find time I will try :)

**Comment by piemanau** [comment]
I might, if I do it will be a couple of days atleast

**Comment by e-splat** [comment]
and for 1.18.2 :)?

**Comment by piemanau** [comment]
Just updated to 1.19.x with https://github.com/LimeShulkerBox/multiplayer-button/tree/1.19.2

**Comment by e-splat** [comment]
yes but when 1.18.2?

**Comment by piemanau** [comment]
> yes but when 1.18.2?

Sorry for the late reply, working on it now

**Comment by piemanau** [comment]
Completed, uploading to CF and modrinth now
