### ISSUE TITLE
1.0.0 Isn't compatible with 1.19.3 (now fabric)

### ISSUE THREAD

**Issue by Aces-and-Jacks** [LimeShulkerBox/multiplayer-button#2]
When I load into my world and go to the settings tab minecraft crashes

https://mclo.gs/3XQWvFL

**Comment by Aces-and-Jacks** [comment]
The version listed on modrinth at least. also I was wondering if not linking the issues tab on modrinth to GitHub intentional or just forgot?

**Comment by piemanau** [comment]
I don't support quilt, sorry

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/w71bRys

now it's fabric

**Comment by pitzlthepixel** [comment]
can you make it so that it supports 1.19.4

**Comment by pitzlthepixel** [comment]
my game is also crashing in 1.19.4

**Comment by piemanau** [comment]
fixed 1.19.4
