### ISSUE TITLE
Incompatibility with OrganizablePlayScreens

### ISSUE THREAD

**Issue by SkyWors** [LimeShulkerBox/multiplayer-button#6]
Hey!

There is an incompatibility with [OrganizablePlayScreens](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric)'s folders, when i enter in one of it, Multiplayer-Button make me quit the current server instead of display the list of associated servers.

**Comment by piemanau** [comment]
I just tested and I could indeed reproduce it. However by seeing what it does it may have to be fixed by the other developer. I will look into it more and let you know.

**Comment by piemanau** [comment]
Do you know how to build java projects? I think I have fixed it but I would like you to test before I release it. I have committed it to the repository, let me know, thanks

**Comment by SkyWors** [comment]
I've just compiled the mods and this version has fixed the bug, thank you very much!

**Comment by piemanau** [comment]
No worries, enjoy
